# Run integration tests against the integ API endpoint
name: test integ
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      # It's totally debatable which is better here: fail-fast or not.
      # Failing fast will use fewer cloud resources, in theory.
      #    But if the tests are slightly flaky (fail to pip install something)
      #    Then one flaky install kills lots of jobs that need to be redone.
      #    So the efficiency argument has its limits
      # Failing slow is clearer about what's going on.
      #    This is pretty unambiguous, so we're going with it for now.
      fail-fast: false
      matrix:
        python-version: [
            #"3.6",   # Default on Ubuntu18.04 but openapi-generator fails
            "3.7",
            "3.8",
            "3.9",
            "3.10",
            "3.11",
          ]
        install_numpy: [true, false]
        install_pillow: [true, false]
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: install poetry and build poetry environment
        run: |
          pip install -U pip
          pip install poetry
          poetry install
      - name: setup environment
        run: make install
      - name: install numpy
        if: matrix.install_numpy
        run: |
          poetry run pip install numpy
      - name: install pillow
        if: matrix.install_pillow
        run: |
          poetry run pip install pillow
      - name: run tests
        env:
          # This is associated with the "sdk-integ-test" user, credentials on 1password
          GROUNDLIGHT_API_TOKEN: ${{ secrets.GROUNDLIGHT_API_TOKEN }}
        run: make test-integ
      - name: run docs tests
        run: make test-docs
        env:
          # This is associated with the "sdk-test-prod" user, credentials on 1password
          GROUNDLIGHT_API_TOKEN: ${{ secrets.GROUNDLIGHT_API_TOKEN_PROD }}
